constants:

  cloudfront:
    domain: <%= ENV['STW_CLOUDFRONT_DOMAIN'] %>

  simple_token_web:
    root_url: <%= ENV['STW_ROOT_URL'] %>
    sale_root_url: <%= ENV['STW_SALE_ROOT_URL'] %>
    kyc_root_url: <%= ENV['STW_KYC_ROOT_URL'] %>

  simple_token_api:
    open_timeout: 50
    read_timeout: 50

  pepo_campaign:
    encrypted_client_id: <%= ENV['STW_CAMPAIGN_ENCRYPTED_CLIENT_ID'] %>
    encrypted_list_id: <%= ENV['STW_CAMPAIGN_ENCRYPTED_LIST_ID']%>

  st_token_sale:
    user_register_dates:
      early_access_register_start_date:  <%= ENV['STW_EARLY_ACCESS_REGISTER_START_DATE'] %>
      early_access_register_end_date:  <%= ENV['STW_EARLY_ACCESS_REGISTER_END_DATE'] %>
    sale_dates:
      early_access_sale_start_date:  <%= ENV['STW_EARLY_ACCESS_SALE_START_DATE'] %>
      general_access_sale_start_date:  <%= ENV['STW_GENERAL_ACCESS_SALE_START_DATE'] %>
      general_access_sale_end_date:  <%= ENV['STW_GENERAL_ACCESS_SALE_END_DATE'] %>
    sale_milestones:
      soft_cap: 50000000
      target: 100000000
      kicker: 120000000
      power: 180000000
      hard_cap: 240000000

  recaptcha:
    site_key: <%= ENV['STW_RECAPTCHA_SITE_KEY'] %>

  api_sidekiq_interface:
    redis_url: <%= ENV['STW_REDIS_ENDPOINT'] %>
    admin_user: 'sidekiq.admin'
    admin_pw: <%= ENV['STW_SK_ADMIN_PW'] %>

  local_path:
    geo_ip_file: <%= ENV['STW_GEOIP_FILE_WITH_PATH'] %>

  memcached:
    instances: <%= ENV['STW_MEMCACHED_INSTANCES'] %>

  company_other_product_urls:
    root_url: <%= ENV['COMPANY_ROOT_URL'] %>
    kit_root_url: <%= ENV['COMPANY_KIT_ROOT_URL'] %>
    view_root_url: <%= ENV['COMPANY_VIEW_ROOT_URL'] %>