countries:
- ABKHAZIA
- AFGHANISTAN
- ALAND ISLANDS
- ALBANIA
- ALGERIA
- AMERICAN SAMOA
- ANDORRA
- ANGOLA
- ANGUILLA
- ANTARCTICA
- ANTIGUA AND BARBUDA
- ARGENTINA
- ARMENIA
- ARUBA
- ASCENSION
- ASHMORE AND CARTIER ISLANDS
- AUSTRALIA
- AUSTRALIAN ANTARCTIC TERRITORY
- AUSTRIA
- AZERBAIJAN
- BAHAMAS
- BAHRAIN
- BAKER ISLAND
- BANGLADESH
- BARBADOS
- BELARUS
- BELGIUM
- BELIZE
- BENIN
- BERMUDA
- BHUTAN
- BOLIVIA
- BOSNIA AND HERZEGOVINA
- BOTSWANA
- BOUVET ISLAND
- BRAZIL
- BRITISH ANTARCTIC TERRITORY
- BRITISH INDIAN OCEAN TERRITORY
- BRITISH SOVEREIGN BASE AREAS
- BRITISH VIRGIN ISLANDS
- BRUNEI
- BULGARIA
- BURKINA FASO
- BURMA (REPUBLIC OF THE UNION OF MYANMAR)
- BURUNDI
- CAMBODIA
- CAMEROON
- CANADA
- CAPE VERDE
- CARIBBEAN NETHERLANDS
- CAYMAN ISLANDS
- CENTRAL AFRICAN REPUBLIC
- CHAD
- CHILE
- CHINA
- CHRISTMAS ISLAND
- CLIPPERTON ISLAND
- COCOS (KEELING) ISLANDS
- COLOMBIA
- COMOROS
- CONGO (REPUBLIC OF)
- COOK ISLANDS
- CORAL SEA ISLANDS
- COSTA RICA
- COTE D'IVOIRE (IVORY COAST)
- CROATIA
- CUBA
- CURACAO
- CYPRUS
- CZECH REPUBLIC
- DEMOCRATIC REPUBLIC OF THE CONGO
- DENMARK
- DJIBOUTI
- DOMINICA
- DOMINICAN REPUBLIC
- ECUADOR
- EGYPT
- EL SALVADOR
- EQUATORIAL GUINEA
- ERITREA
- ESTONIA
- ETHIOPIA
- FALKLAND ISLANDS
- FAROE ISLANDS
- FIJI
- FINLAND
- FRANCE
- FRENCH GUIANA
- FRENCH POLYNESIA
- FRENCH SOUTHERN AND ANTARCTIC LANDS
- FRENCH SOUTHERN TERRITORIES
- GABON
- GAMBIA
- GEORGIA
- GERMANY
- GHANA
- GIBRALTAR
- GREECE
- GREENLAND
- GRENADA
- GUADELOUPE
- GUAM
- GUATEMALA
- GUERNSEY
- GUINEA
- GUINEA-BISSAU
- GUYANA
- HAITI
- HEARD AND MCDONALD ISLANDS
- HONDURAS
- HONG KONG
- HOWLAND ISLAND
- HUNGARY
- ICELAND
- INDIA
- INDONESIA
- IRAN
- IRAQ
- IRELAND
- ISLE OF MAN
- ISRAEL
- ITALY
- JAMAICA
- JAPAN
- JARVIS ISLAND
- JERSEY
- JOHNSTON ATOLL
- JORDAN
- KAZAKHSTAN
- KENYA
- KINGMAN REEF
- KIRIBATI
- KOSOVO
- KUWAIT
- KYRGYZSTAN
- LAOS
- LATVIA
- LEBANON
- LESOTHO
- LIBERIA
- LIBYA
- LIECHTENSTEIN
- LITHUANIA
- LUXEMBOURG
- MACAU
- MACEDONIA
- MADAGASCAR
- MALAWI
- MALAYSIA
- MALDIVES
- MALI
- MALTA
- MARSHALL ISLANDS
- MARTINIQUE
- MAURITANIA
- MAURITIUS
- MAYOTTE
- MEXICO
- MICRONESIA
- MIDWAY ISLANDS
- MOLDOVA
- MONACO
- MONGOLIA
- MONTENEGRO
- MONTSERRAT
- MOROCCO
- MOZAMBIQUE
- NAGORNO-KARABAKH
- NAMIBIA
- NAURU
- NAVASSA ISLAND
- NEPAL
- NETHERLANDS
- NEW CALEDONIA
- NEW ZEALAND
- NICARAGUA
- NIGER
- NIGERIA
- NIUE
- NORFOLK ISLAND
- NORTH KOREA
- NORTHERN CYPRUS
- NORTHERN MARIANA ISLANDS
- NORWAY
- OMAN
- PAKISTAN
- PALAU
- PALESTINE
- PALMYRA ATOLL
- PANAMA
- PAPUA NEW GUINEA
- PARAGUAY
- PERU
- PETER I ISLAND
- PHILIPPINES
- PITCAIRN
- PITCAIRN ISLANDS
- POLAND
- PORTUGAL
- PRIDNESTROVIE (TRANSNISTRIA)
- PUERTO RICO
- QATAR
- QUEEN MAUD LAND
- REUNION
- ROMANIA
- ROSS DEPENDENCY
- RUSSIAN FEDERATION
- RWANDA
- SAINT BARTHELEMY
- SAINT HELENA
- SAINT KITTS AND NEVIS
- SAINT LUCIA
- SAINT MARTIN (FRANCE)
- SAINT MARTIN (NETHERLANDS)
- SAINT PIERRE AND MIQUELON
- SAINT VINCENT AND GRENADINES
- SAMOA
- SAN MARINO
- SAO TOME AND PRINCIPE
- SAUDI ARABIA
- SENEGAL
- SERBIA
- SEYCHELLES
- SIERRA LEONE
- SINGAPORE
- SLOVAKIA
- SLOVENIA
- SOLOMON ISLANDS
- SOMALIA
- SOMALILAND
- SOUTH AFRICA
- SOUTH GEORGIA & SOUTH SANDWICH ISLANDS
- SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
- SOUTH KOREA
- SOUTH OSSETIA
- SOUTH SUDAN
- SPAIN
- SRI LANKA
- SUDAN
- SURINAME
- SVALBARD AND JAN MAYEN ISLANDS
- SWAZILAND
- SWEDEN
- SWITZERLAND
- SYRIA
- TAIWAN
- TAJIKISTAN
- TANZANIA
- THAILAND
- TIMOR-LESTE
- TOGO
- TOKELAU
- TONGA
- TRINIDAD AND TOBAGO
- TRISTAN DA CUNHA
- TUNISIA
- TURKEY
- TURKMENISTAN
- TURKS AND CAICOS ISLANDS
- TUVALU
- UGANDA
- UKRAINE
- UNITED ARAB EMIRATES
- UNITED KINGDOM
- UNITED STATES MINOR OUTLYING ISLANDS
- UNITED STATES OF AMERICA
- UNITED STATES VIRGIN ISLANDS
- URUGUAY
- UZBEKISTAN
- VANUATU
- VATICAN
- VENEZUELA
- VIETNAM
- WAKE ISLAND
- WALLIS AND FUTUNA ISLANDS
- WESTERN SAHARAN
- YEMEN
- ZAMBIA
- ZIMBABWE

nationalities:
- ABKHAZIAN
- AFGHANI
- ALANDIC
- ALBANIAN
- ALGERIAN
- U.S. TERRITORY
- ANDORRAN
- ANGOLAN
- BRITISH OVERSEAS TERRITORY
- ANTARCTIC
- ANTIGUAN
- ARGENTINE
- ARMENIAN
- ARUBIAN
- ASCENSION
- AUSTRALIAN EXTERNAL TERRITORY
- AUSTRALIAN
- AUSTRALIAN ANTARCTIC TERRITORY
- AUSTRIAN
- AZERBAIJANI
- BAHAMEESE
- BAHRAINIAN
- BAKER ISLAND
- BANGLADESHI
- BARBADIAN
- BELARUSIAN
- BELGIAN
- BELIZEAN
- BENINESE
- BRITISH OVERSEAS TERRITORY
- BHUTANESE
- BOLIVIAN
- BOSNIAN
- MOTSWANA
- BOUVET ISLAND
- BRAZILIAN
- BRITISH ANTARCTIC TERRITORY
- BRITISH INDIAN OCEAN TERRITORY
- BRITISH SOVEREIGN BASE AREAS
- BRITISH OVERSEAS TERRITORY
- BRUNEIAN
- BULGARIAN
- BURKINABE
- MYANMAR
- BURUNDIAN
- CAMBODIAN
- CAMEROONIAN
- CANADIAN
- CAPE VERDEAN
- CARIBBEAN NETHERLANDS
- BRITISH OVERSEAS TERRITORY
- CENTRAL AFRICAN
- CHADIAN
- CHILEAN
- CHINESE
- AUSTRALIAN EXTERNAL TERRITORY
- CLIPPERTON ISLAND
- AUSTRALIAN EXTERNAL TERRITORY
- COLOMBIAN
- COMORAN
- CONGOLESE
- COOK ISLANDER
- AUSTRALIAN EXTERNAL TERRITORY
- COSTA RICAN
- IVORIAN
- CROATIAN
- CUBAN
- CURACAOAN
- CYPRIOT
- CZECH
- CONGOLESE
- DANISH
- DJIBOUTIAN
- DOMINICAN
- DOMINICAN
- ECUADOREAN
- EGYPTIAN
- SALVADOREAN
- EQUATORIAL GUINEAN
- ERITREAN
- ESTONIAN
- ETHIOPIAN
- BRITISH OVERSEAS TERRITORY
- FAROESE
- FIJIAN
- FINNISH
- FRENCH
- FRENCH GUIANESE
- FRENCH OVERSEAS COLLECTIVITY
- FRENCH SOUTHERN AND ANTARCTIC LANDS
- FRENCH SOUTHERN TERRITORIES
- GABONESE
- GAMBIAN
- GEORGIAN
- GERMAN
- GHANAIAN
- GIBRALTARIAN
- GREEK
- GREENLANDER
- GRENADIAN
- GUADELOUPEAN
- GUAMANIAN
- GUATEMALAN
- GUERNSEY
- GUINEAN
- GUINEAN
- GUYANESE
- HAITIAN
- AUSTRALIAN EXTERNAL TERRITORY
- HONDURAN
- HONG KONG
- HOWLAND ISLAND
- HUNGARIAN
- ICELANDER
- INDIAN
- INDONESIAN
- IRANIAN
- IRAQI
- IRISH
- MANX
- ISRAELI
- ITALIAN
- JAMAICAN
- JAPANESE
- JARVIS ISLAND
- JERSEY
- JOHNSTON ATOLL
- JORDANIAN
- KAZAKHSTANI
- KENYAN
- KINGMAN REEF
- I-KIRIBATI
- KOSOVAR
- KUWAITI
- KYRGYZSTANI
- LAOTIAN
- LATVIAN
- LEBANESE
- MOSOTHO
- LIBERIAN
- LIBYAN
- LIECHTENSTEINER
- LITHUNIAN
- LUXEMBOURGER
- MACANESE
- MACEDONIAN
- MALAGASY
- MALAWIAN
- MALAYSIAN
- MALDIVAN
- MALIAN
- MALTESE
- MARSHALLESE
- MARTINICAN
- MAURITANIAN
- MAURITIAN
- MAHORAN
- MEXICAN
- MICRONESIAN
- U.S. TERRITORY
- MOLDOVAN
- MONACAN
- MONGOLIAN
- MONTENEGRIN
- MONTSERRATIAN
- MOROCCAN
- MOZAMBICAN
- NAGORNO-KARABAKH
- NAMIBIAN
- NAURUAN
- NAVASSA ISLAND
- NEPALESE
- DUTCH
- NEW CALEDONIAN
- NEW ZEALANDER
- NICARAGUAN
- NIGERIEN
- NIGERIAN
- NIUEAN
- NORFOLK ISLANDER
- NORTH KOREAN
- U.S. TERRITORY
- U.S. TERRITORY
- NORWEGIAN
- OMANI
- PAKISTANI
- PALAUAN
- PALESTINIAN
- PALMYRA ATOLL
- PANAMANIAN
- PAPUA NEW GUINEAN
- PARAGUAYAN
- PERUVIAN
- PETER I ISLAND
- FILIPINO
- PITCAIRN ISLANDER
- BRITISH OVERSEAS TERRITORY
- POLISH
- PORTUGUESE
- PRIDNESTROVIE (TRANSNISTRIA)
- PUERTO RICAN
- QATARI
- QUEEN MAUD LAND
- FRENCH OVERSEAS REGION
- ROMANIAN
- ROSS DEPENDENCY
- RUSSIAN
- RWANDAN
- FRENCH OVERSEAS COLLECTIVITY
- BRITISH OVERSEAS TERRITORY
- KITTIAN
- SAINT LUCIAN
- FRENCH OVERSEAS COLLECTIVITY
- DUTCH
- SAINT-PIERRAIS
- SAINT VINCENTIAN
- SAMOAN
- SANMARINESE
- SAO TOMEAN
- SAUDI ARABIAN
- SENEGALESE
- SERBIAN
- SEYCHELLOIS
- SIERRA LEONEAN
- SINGAPOREAN
- SLOVAKIAN
- SLOVENIAN
- SOLOMON ISLANDER
- SOMALI
- SOMALILAND
- SOUTH AFRICAN
- BRITISH OVERSEAS TERRITORY
- BRITISH OVERSEAS TERRITORY
- SOUTH KOREAN
- SOUTH OSSETIA
- SOUTH SUDANESE
- SPANISH
- SRI LANKAN
- SUDANESE
- SURINAMER
- SVALBARD AND JAN MAYEN ISLANDS
- SWAZI
- SWEDISH
- SWISS
- SYRIAN
- TAIWANESE
- TAJIKISTANI
- TANZANIAN
- THAI
- TIMORESE
- TOGOLESE
- TOKELAUAN
- TONGAN
- TRINIDADIAN
- TRISTAN DA CUNHA
- TUNISIAN
- TURKISH
- TURKMEN
- BRITISH OVERSEAS TERRITORY
- TUVALUAN
- UGANDAN
- UKRAINIAN
- EMIRIAN
- BRITISH
- U.S. TERRITORY
- AMERICAN
- U.S. TERRITORY
- URUGUAYAN
- UZBEKISTANI
- NI-VANUATU
- VATICAN
- VENEZUELAN
- VIETNAMESE
- WAKE ISLAND
- FRENCH OVERSEAS COLLECTIVITY
- WESTERN SAHARAN
- YEMENI
- ZAMBIAN
- ZIMBABWEAN
