---
:countries:
- ABKHAZIA
- ALAND ISLANDS
- ALBANIA
- ALGERIA
- AMERICAN SAMOA
- ANDORRA
- ANGOLA
- ANGUILLA
- ANTARCTICA
- ANTIGUA AND BARBUDA
- ARGENTINA
- ARMENIA
- ARUBA
- ASCENSION
- ASHMORE AND CARTIER ISLANDS
- AUSTRALIA
- AUSTRALIAN ANTARCTIC TERRITORY
- AUSTRIA
- AZERBAIJAN
- BAHAMAS
- BAHRAIN
- BAKER ISLAND
- BANGLADESH
- BARBADOS
- BELARUS
- BELGIUM
- BELIZE
- BENIN
- BERMUDA
- BHUTAN
- BOLIVIA
- BOTSWANA
- BOUVET ISLAND
- BRAZIL
- BRITISH ANTARCTIC TERRITORY
- BRITISH INDIAN OCEAN TERRITORY
- BRITISH SOVEREIGN BASE AREAS
- BRITISH VIRGIN ISLANDS
- BRUNEI
- BULGARIA
- BURKINA FASO
- BURMA (REPUBLIC OF THE UNION OF MYANMAR)
- BURUNDI
- CAMBODIA
- CAMEROON
- CANADA
- CAPE VERDE
- CARIBBEAN NETHERLANDS
- CAYMAN ISLANDS
- CHAD
- CHILE
- CHRISTMAS ISLAND
- CLIPPERTON ISLAND
- COCOS (KEELING) ISLANDS
- COLOMBIA
- COMOROS
- CONGO (REPUBLIC OF)
- COOK ISLANDS
- CORAL SEA ISLANDS
- COSTA RICA
- COTE D'IVOIRE (IVORY COAST)
- CROATIA
- CURACAO
- CYPRUS
- CZECH REPUBLIC
- DENMARK
- DJIBOUTI
- DOMINICA
- DOMINICAN REPUBLIC
- ECUADOR
- EGYPT
- EL SALVADOR
- EQUATORIAL GUINEA
- ESTONIA
- FALKLAND ISLANDS
- FAROE ISLANDS
- FIJI
- FINLAND
- FRANCE
- FRENCH GUIANA
- FRENCH POLYNESIA
- FRENCH SOUTHERN AND ANTARCTIC LANDS
- FRENCH SOUTHERN TERRITORIES
- GABON
- GAMBIA
- GEORGIA
- GERMANY
- GHANA
- GIBRALTAR
- GREECE
- GREENLAND
- GRENADA
- GUADELOUPE
- GUAM
- GUATEMALA
- GUERNSEY
- GUINEA
- GUYANA
- HAITI
- HEARD AND MCDONALD ISLANDS
- HONDURAS
- HONG KONG
- HOWLAND ISLAND
- HUNGARY
- ICELAND
- INDIA
- INDONESIA
- IRELAND
- ISLE OF MAN
- ISRAEL
- ITALY
- JAMAICA
- JAPAN
- JARVIS ISLAND
- JERSEY
- JOHNSTON ATOLL
- JORDAN
- KAZAKHSTAN
- KENYA
- KINGMAN REEF
- KIRIBATI
- KOSOVO
- KUWAIT
- KYRGYZSTAN
- LAOS
- LATVIA
- LESOTHO
- LIBERIA
- LIECHTENSTEIN
- LITHUANIA
- LUXEMBOURG
- MACAU
- MACEDONIA
- MADAGASCAR
- MALAWI
- MALAYSIA
- MALDIVES
- MALI
- MALTA
- MARSHALL ISLANDS
- MARTINIQUE
- MAURITANIA
- MAURITIUS
- MAYOTTE
- MEXICO
- MICRONESIA
- MIDWAY ISLANDS
- MOLDOVA
- MONACO
- MONGOLIA
- MONTENEGRO
- MONTSERRAT
- MOROCCO
- MOZAMBIQUE
- NAGORNO-KARABAKH
- NAMIBIA
- NAURU
- NAVASSA ISLAND
- NEPAL
- NETHERLANDS
- NEW CALEDONIA
- NICARAGUA
- NIGER
- NIGERIA
- NIUE
- NORFOLK ISLAND
- NORTHERN CYPRUS
- NORTHERN MARIANA ISLANDS
- NORWAY
- OMAN
- PAKISTAN
- PALAU
- PALESTINE
- PALMYRA ATOLL
- PANAMA
- PAPUA NEW GUINEA
- PARAGUAY
- PERU
- PETER I ISLAND
- PHILIPPINES
- PITCAIRN
- PITCAIRN ISLANDS
- POLAND
- PORTUGAL
- PRIDNESTROVIE (TRANSNISTRIA)
- PUERTO RICO
- QATAR
- QUEEN MAUD LAND
- REUNION
- ROMANIA
- ROSS DEPENDENCY
- RUSSIAN FEDERATION
- RWANDA
- SAINT BARTHELEMY
- SAINT HELENA
- SAINT KITTS AND NEVIS
- SAINT LUCIA
- SAINT MARTIN (FRANCE)
- SAINT MARTIN (NETHERLANDS)
- SAINT PIERRE AND MIQUELON
- SAINT VINCENT AND GRENADINES
- SAMOA
- SAN MARINO
- SAO TOME AND PRINCIPE
- SAUDI ARABIA
- SENEGAL
- SERBIA
- SEYCHELLES
- SIERRA LEONE
- SINGAPORE
- SLOVAKIA
- SLOVENIA
- SOLOMON ISLANDS
- SOMALILAND
- SOUTH AFRICA
- SOUTH GEORGIA & SOUTH SANDWICH ISLANDS
- SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
- SOUTH KOREA
- SOUTH OSSETIA
- SPAIN
- SRI LANKA
- SURINAME
- SVALBARD AND JAN MAYEN ISLANDS
- SWAZILAND
- SWEDEN
- SWITZERLAND
- TAIWAN
- TAJIKISTAN
- TANZANIA
- THAILAND
- TIMOR-LESTE
- TOGO
- TOKELAU
- TONGA
- TRINIDAD AND TOBAGO
- TRISTAN DA CUNHA
- TUNISIA
- TURKEY
- TURKMENISTAN
- TURKS AND CAICOS ISLANDS
- TUVALU
- UKRAINE
- UNITED ARAB EMIRATES
- UNITED KINGDOM
- UNITED STATES MINOR OUTLYING ISLANDS
- UNITED STATES OF AMERICA
- UNITED STATES VIRGIN ISLANDS
- URUGUAY
- UZBEKISTAN
- VATICAN
- VENEZUELA
- VIETNAM
- WAKE ISLAND
- WALLIS AND FUTUNA ISLANDS
- WESTERN SAHARAN
- ZAMBIA
- ZIMBABWE