---
:nationalities:
- ABKHAZIAN
- AFGHANI
- ALANDIC
- ALBANIAN
- ALGERIAN
- U.S. TERRITORY
- ANDORRAN
- ANGOLAN
- BRITISH OVERSEAS TERRITORY
- ANTARCTIC
- ANTIGUAN
- ARGENTINE
- ARMENIAN
- ARUBIAN
- ASCENSION
- AUSTRALIAN EXTERNAL TERRITORY
- AUSTRALIAN
- AUSTRALIAN ANTARCTIC TERRITORY
- AUSTRIAN
- AZERBAIJANI
- BAHAMEESE
- BAHRAINIAN
- BAKER ISLAND
- BANGLADESHI
- BARBADIAN
- BELARUSIAN
- BELGIAN
- BELIZEAN
- BENINESE
- BRITISH OVERSEAS TERRITORY
- BHUTANESE
- BOLIVIAN
- BOSNIAN
- MOTSWANA
- BOUVET ISLAND
- BRAZILIAN
- BRITISH ANTARCTIC TERRITORY
- BRITISH INDIAN OCEAN TERRITORY
- BRITISH SOVEREIGN BASE AREAS
- BRITISH OVERSEAS TERRITORY
- BRUNEIAN
- BULGARIAN
- BURKINABE
- MYANMAR
- BURUNDIAN
- CAMBODIAN
- CAMEROONIAN
- CANADIAN
- CAPE VERDEAN
- CARIBBEAN NETHERLANDS
- BRITISH OVERSEAS TERRITORY
- CENTRAL AFRICAN
- CHADIAN
- CHILEAN
- CHINESE
- AUSTRALIAN EXTERNAL TERRITORY
- CLIPPERTON ISLAND
- AUSTRALIAN EXTERNAL TERRITORY
- COLOMBIAN
- COMORAN
- CONGOLESE
- COOK ISLANDER
- AUSTRALIAN EXTERNAL TERRITORY
- COSTA RICAN
- IVORIAN
- CROATIAN
- CUBAN
- CURACAOAN
- CYPRIOT
- CZECH
- CONGOLESE
- DANISH
- DJIBOUTIAN
- DOMINICAN
- DOMINICAN
- ECUADOREAN
- EGYPTIAN
- SALVADOREAN
- EQUATORIAL GUINEAN
- ERITREAN
- ESTONIAN
- ETHIOPIAN
- BRITISH OVERSEAS TERRITORY
- FAROESE
- FIJIAN
- FINNISH
- FRENCH
- FRENCH GUIANESE
- FRENCH OVERSEAS COLLECTIVITY
- FRENCH SOUTHERN AND ANTARCTIC LANDS
- FRENCH SOUTHERN TERRITORIES
- GABONESE
- GAMBIAN
- GEORGIAN
- GERMAN
- GHANAIAN
- GIBRALTARIAN
- GREEK
- GREENLANDER
- GRENADIAN
- GUADELOUPEAN
- GUAMANIAN
- GUATEMALAN
- GUERNSEY
- GUINEAN
- GUINEAN
- GUYANESE
- HAITIAN
- AUSTRALIAN EXTERNAL TERRITORY
- HONDURAN
- HONG KONG
- HOWLAND ISLAND
- HUNGARIAN
- ICELANDER
- INDIAN
- INDONESIAN
- IRANIAN
- IRAQI
- IRISH
- MANX
- ISRAELI
- ITALIAN
- JAMAICAN
- JAPANESE
- JARVIS ISLAND
- JERSEY
- JOHNSTON ATOLL
- JORDANIAN
- KAZAKHSTANI
- KENYAN
- KINGMAN REEF
- I-KIRIBATI
- KOSOVAR
- KUWAITI
- KYRGYZSTANI
- LAOTIAN
- LATVIAN
- LEBANESE
- MOSOTHO
- LIBERIAN
- LIBYAN
- LIECHTENSTEINER
- LITHUNIAN
- LUXEMBOURGER
- MACANESE
- MACEDONIAN
- MALAGASY
- MALAWIAN
- MALAYSIAN
- MALDIVAN
- MALIAN
- MALTESE
- MARSHALLESE
- MARTINICAN
- MAURITANIAN
- MAURITIAN
- MAHORAN
- MEXICAN
- MICRONESIAN
- U.S. TERRITORY
- MOLDOVAN
- MONACAN
- MONGOLIAN
- MONTENEGRIN
- MONTSERRATIAN
- MOROCCAN
- MOZAMBICAN
- NAGORNO-KARABAKH
- NAMIBIAN
- NAURUAN
- NAVASSA ISLAND
- NEPALESE
- DUTCH
- NEW CALEDONIAN
- NEW ZEALANDER
- NICARAGUAN
- NIGERIEN
- NIGERIAN
- NIUEAN
- NORFOLK ISLANDER
- NORTH KOREAN
- U.S. TERRITORY
- U.S. TERRITORY
- NORWEGIAN
- OMANI
- PAKISTANI
- PALAUAN
- PALESTINIAN
- PALMYRA ATOLL
- PANAMANIAN
- PAPUA NEW GUINEAN
- PARAGUAYAN
- PERUVIAN
- PETER I ISLAND
- FILIPINO
- PITCAIRN ISLANDER
- BRITISH OVERSEAS TERRITORY
- POLISH
- PORTUGUESE
- PRIDNESTROVIE (TRANSNISTRIA)
- PUERTO RICAN
- QATARI
- QUEEN MAUD LAND
- FRENCH OVERSEAS REGION
- ROMANIAN
- ROSS DEPENDENCY
- RUSSIAN
- RWANDAN
- FRENCH OVERSEAS COLLECTIVITY
- BRITISH OVERSEAS TERRITORY
- KITTIAN
- SAINT LUCIAN
- FRENCH OVERSEAS COLLECTIVITY
- DUTCH
- SAINT-PIERRAIS
- SAINT VINCENTIAN
- SAMOAN
- SANMARINESE
- SAO TOMEAN
- SAUDI ARABIAN
- SENEGALESE
- SERBIAN
- SEYCHELLOIS
- SIERRA LEONEAN
- SINGAPOREAN
- SLOVAKIAN
- SLOVENIAN
- SOLOMON ISLANDER
- SOMALI
- SOMALILAND
- SOUTH AFRICAN
- BRITISH OVERSEAS TERRITORY
- BRITISH OVERSEAS TERRITORY
- SOUTH KOREAN
- SOUTH OSSETIA
- SOUTH SUDANESE
- SPANISH
- SRI LANKAN
- SUDANESE
- SURINAMER
- SVALBARD AND JAN MAYEN ISLANDS
- SWAZI
- SWEDISH
- SWISS
- SYRIAN
- TAIWANESE
- TAJIKISTANI
- TANZANIAN
- THAI
- TIMORESE
- TOGOLESE
- TOKELAUAN
- TONGAN
- TRINIDADIAN
- TRISTAN DA CUNHA
- TUNISIAN
- TURKISH
- TURKMEN
- BRITISH OVERSEAS TERRITORY
- TUVALUAN
- UGANDAN
- UKRAINIAN
- EMIRIAN
- BRITISH
- U.S. TERRITORY
- AMERICAN
- U.S. TERRITORY
- URUGUAYAN
- UZBEKISTANI
- NI-VANUATU
- VATICAN
- VENEZUELAN
- VIETNAMESE
- WAKE ISLAND
- FRENCH OVERSEAS COLLECTIVITY
- WESTERN SAHARAN
- YEMENI
- ZAMBIAN
- ZIMBABWEAN