---
:nationalities:
- ABKHAZIAN
- ALANDIC
- ALBANIAN
- ALGERIAN
- AMERICAN
- ANDORRAN
- ANGOLAN
- ANTARCTIC
- ANTIGUAN
- ARGENTINE
- ARMENIAN
- ARUBIAN
- ASCENSION
- AUSTRALIAN
- AUSTRALIAN ANTARCTIC TERRITORY
- AUSTRALIAN EXTERNAL TERRITORY
- AUSTRIAN
- AZERBAIJANI
- BAHAMEESE
- BAHRAINIAN
- BAKER ISLAND
- BANGLADESHI
- BARBADIAN
- BELARUSIAN
- BELGIAN
- BELIZEAN
- BENINESE
- BHUTANESE
- BOLIVIAN
- BOUVET ISLAND
- BRAZILIAN
- BRITISH
- BRITISH ANTARCTIC TERRITORY
- BRITISH INDIAN OCEAN TERRITORY
- BRITISH OVERSEAS TERRITORY
- BRITISH SOVEREIGN BASE AREAS
- BRUNEIAN
- BULGARIAN
- BURKINABE
- BURUNDIAN
- CAMBODIAN
- CAMEROONIAN
- CANADIAN
- CAPE VERDEAN
- CARIBBEAN NETHERLANDS
- CHADIAN
- CHILEAN
- CHINESE
- CLIPPERTON ISLAND
- COLOMBIAN
- COMORAN
- CONGOLESE
- COOK ISLANDER
- COSTA RICAN
- CROATIAN
- CUBAN
- CURACAOAN
- CYPRIOT
- CZECH
- DANISH
- DJIBOUTIAN
- DOMINICAN
- DUTCH
- ECUADOREAN
- EGYPTIAN
- EMIRIAN
- EQUATORIAL GUINEAN
- ESTONIAN
- FAROESE
- FIJIAN
- FILIPINO
- FINNISH
- FRENCH
- FRENCH GUIANESE
- FRENCH OVERSEAS COLLECTIVITY
- FRENCH OVERSEAS REGION
- FRENCH SOUTHERN AND ANTARCTIC LANDS
- FRENCH SOUTHERN TERRITORIES
- GABONESE
- GAMBIAN
- GEORGIAN
- GERMAN
- GHANAIAN
- GIBRALTARIAN
- GREEK
- GREENLANDER
- GRENADIAN
- GUADELOUPEAN
- GUAMANIAN
- GUATEMALAN
- GUERNSEY
- GUINEAN
- GUYANESE
- HAITIAN
- HONDURAN
- HONG KONG
- HOWLAND ISLAND
- HUNGARIAN
- I-KIRIBATI
- ICELANDER
- INDIAN
- INDONESIAN
- IRISH
- ISRAELI
- ITALIAN
- IVORIAN
- JAMAICAN
- JAPANESE
- JARVIS ISLAND
- JERSEY
- JOHNSTON ATOLL
- JORDANIAN
- KAZAKHSTANI
- KENYAN
- KINGMAN REEF
- KITTIAN
- KOSOVAR
- KUWAITI
- KYRGYZSTANI
- LAOTIAN
- LATVIAN
- LIBERIAN
- LIECHTENSTEINER
- LITHUNIAN
- LUXEMBOURGER
- MACANESE
- MACEDONIAN
- MAHORAN
- MALAGASY
- MALAWIAN
- MALAYSIAN
- MALDIVAN
- MALIAN
- MALTESE
- MANX
- MARSHALLESE
- MARTINICAN
- MAURITANIAN
- MAURITIAN
- MEXICAN
- MICRONESIAN
- MOLDOVAN
- MONACAN
- MONGOLIAN
- MONTENEGRIN
- MONTSERRATIAN
- MOROCCAN
- MOSOTHO
- MOTSWANA
- MOZAMBICAN
- MYANMAR
- NAGORNO-KARABAKH
- NAMIBIAN
- NAURUAN
- NAVASSA ISLAND
- NEPALESE
- NEW CALEDONIAN
- NEW ZEALANDER
- NI-VANUATU
- NICARAGUAN
- NIGERIAN
- NIGERIEN
- NIUEAN
- NORFOLK ISLANDER
- NORWEGIAN
- OMANI
- PAKISTANI
- PALAUAN
- PALESTINIAN
- PALMYRA ATOLL
- PANAMANIAN
- PAPUA NEW GUINEAN
- PARAGUAYAN
- PERUVIAN
- PETER I ISLAND
- PITCAIRN ISLANDER
- POLISH
- PORTUGUESE
- PRIDNESTROVIE (TRANSNISTRIA)
- PUERTO RICAN
- QATARI
- QUEEN MAUD LAND
- ROMANIAN
- ROSS DEPENDENCY
- RUSSIAN
- RWANDAN
- SAINT LUCIAN
- SAINT VINCENTIAN
- SAINT-PIERRAIS
- SALVADOREAN
- SAMOAN
- SANMARINESE
- SAO TOMEAN
- SAUDI ARABIAN
- SENEGALESE
- SERBIAN
- SEYCHELLOIS
- SIERRA LEONEAN
- SINGAPOREAN
- SLOVAKIAN
- SLOVENIAN
- SOLOMON ISLANDER
- SOMALILAND
- SOUTH AFRICAN
- SOUTH KOREAN
- SOUTH OSSETIA
- SPANISH
- SRI LANKAN
- SURINAMER
- SVALBARD AND JAN MAYEN ISLANDS
- SWAZI
- SWEDISH
- SWISS
- TAIWANESE
- TAJIKISTANI
- TANZANIAN
- THAI
- TIMORESE
- TOGOLESE
- TOKELAUAN
- TONGAN
- TRINIDADIAN
- TRISTAN DA CUNHA
- TUNISIAN
- TURKISH
- TURKMEN
- TUVALUAN
- U.S. TERRITORY
- UKRAINIAN
- URUGUAYAN
- UZBEKISTANI
- VATICAN
- VENEZUELAN
- VIETNAMESE
- WAKE ISLAND
- WESTERN SAHARAN
- ZAMBIAN
- ZIMBABWEAN